# Generated by Django 3.0.6 on 2020-05-11 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CC', '0003_auto_20200508_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
