# Generated by Django 3.0.6 on 2020-05-11 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CC', '0004_category_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='total',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
