# Generated by Django 3.0.6 on 2020-05-11 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CC', '0005_product_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='children',
            field=models.ManyToManyField(blank=True, null=True, related_name='_category_children_+', to='CC.Category'),
        ),
    ]
