# Generated by Django 3.0.6 on 2020-05-12 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CC', '0006_category_children'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='children',
            field=models.ManyToManyField(related_name='_category_children_+', to='CC.Category'),
        ),
    ]
