# Generated by Django 3.0.6 on 2020-05-13 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20200512_1812'),
        ('CC', '0008_orderstatus_shipping'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_info', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user.profile_info')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.IntegerField()),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='CC.Cart')),
                ('shipping', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='CC.Shipping')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='CC.OrderStatus')),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('unit_price', models.IntegerField()),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='CC.Cart')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='CC.Product')),
            ],
        ),
    ]
