# Generated by Django 3.0.6 on 2020-05-13 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CC', '0010_remove_category_children'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='product',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='prod_id',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='prod_name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
