# Generated by Django 3.0.6 on 2020-05-13 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CC', '0011_auto_20200513_1823'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='session_id',
            field=models.CharField(blank=True, max_length=999, null=True),
        ),
    ]
