# Generated by Django 3.0.6 on 2020-05-14 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CC', '0013_auto_20200513_1906'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='shipping',
        ),
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
        migrations.DeleteModel(
            name='OrderStatus',
        ),
        migrations.DeleteModel(
            name='Shipping',
        ),
    ]
