# Generated by Django 3.0.6 on 2020-05-14 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CC', '0014_auto_20200514_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
