# Generated by Django 3.0.6 on 2020-05-15 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CC', '0015_order_shipping'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='shipping',
        ),
        migrations.AddField(
            model_name='cart',
            name='shipping',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
