# Generated by Django 3.0.6 on 2020-05-12 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200512_1128'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile_info',
            old_name='street_name',
            new_name='address',
        ),
        migrations.RemoveField(
            model_name='profile_info',
            name='house_no',
        ),
    ]
