# Generated by Django 3.0.6 on 2020-05-12 18:12

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0004_search_history'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='search_history',
            new_name='SearchHistory',
        ),
    ]
