# Generated by Django 3.0.6 on 2020-05-13 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20200512_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile_info',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='user.country'),
        ),
    ]
